### ISSUE TITLE
Introduce macros for Atomic operations

### ISSUE THREAD

**Issue by alexandru** [alexandru/sincron#1]
The [Atomic References](https://github.com/monifu/asterix/wiki/Atomic-References) have these high-level utility methods:
- `transform(f: T => T): Unit`
- `transformAndGet(f: T => T): T`
- `getAndTransform(f: Option[T] => T): Option[T]`
- `getAndExtract[U](f: T => (U, T)): U`

Under the hood these are implemented with `compareAndSet` loops, thus sparing the user of doing such loops, which are error prone and tedious. But unfortunately the functions passed to these methods (that `f` in the signature) are [not inlined by the JVM](http://www.azulsystems.com/blog/cliff/2011-04-04-fixing-the-inlining-problem). And because these are low-level primitives, overhead matters, a lot.

We need macros that can transform from this:

``` scala
val state = Atom(Queue(1,2,3,4))
val number = state.transformAndExtract(_.dequeue)
```

Into an ugly and efficient loop like this:

``` scala
val state = Atom(Queue(1,2,3,4))
val number = {
  var keepTrying = true
  var result: U = null

  while (keepTrying) {
    val current = state.get
    val (r, update) = current.dequeue // <-- inlining here

    if (state.compareAndSet(current, update)) {
      keepTrying = false
      result = r
    }
  }
  result
}
```

**Comment by aoprisan** [comment]
I am working on the macros in the **aref-macro** branch. The current situation is:
-  I have created a separate sub-project named **macros** in the atomic folder. The original reason was to have the macros in a separate compilation unit in order to have them override abstract methods, though it didn't help. I saw other projects having macro definitions in a separate sub-projects, I will read more about it.
- I had to change **transformAndExtract** to have the result as an **Option[U]**, in order to support **AnyVal** for **U** and have a single macro definition (you cannot have an **Int** with a **null** value). It just occurred to me now that I could have used the type information to provide a default value for the result, which I will do if the **Option** is too much overhead.
- The function parameter has to be an anonymous function literal in order for it to be inlined properly, using a method argument will not really inline anything (the macro takes as input the tree of the expression passed to these methods).
- A macro cannot override an abstract method, but it can override a method which override an abstract method. Therefore, one option is to have macros implemented in the **Atomic[T]**. The alternative that I am aware so far is to have a trait providing a dummy implementation for the methods to be implemented via macros and mix it with the **Atomic**\* classes, in order to override them.
- I have tests for the macros behaviour, but not for the code they generate (check that a macro generates a piece of code) as while loops in quasiquotes are not equal. I need to look into it more.

**Comment by alexandru** [comment]
@aoprisan when I tried the code, it wasn't compiling under Scala 2.10. And the Travis build was succeeding because the `.travis.yml` script was wrong (bug).

I managed to solve the problem by importing code from the awesome Spire library. It's basically the same thing as you did, it only has some minor differences. For example it doesn't use `c.untypedtree` which was causing problems. And I think the macros are hygienic now, because we are generating names for the variables we create.

Now it builds and compiles under Scala 2.10 as well.
